### PR TITLE
Feat: support for react-navigation@5 (closes #17)

### LINKED ISSUE #17: support events in react-navigation v5
the events changed, see https://reactnavigation.org/docs/navigation-events

### PR DESCRIPTION
**Pull request by JPeer264**
references:

- https://reactnavigation.org/docs/navigation-prop#isfocused---query-the-focused-state-of-the-screen
- https://reactnavigation.org/docs/upgrading-from-4.x#higher-order-components
- https://reactnavigation.org/docs/navigation-events/

### CODE REVIEW

**Comment by JPeer264** [comment]
It drops the support for v4 though

**Comment by vonovak** [comment]
@JPeer264 thanks for the PR. I'd love to add support for version 5, but I'd prefer for that to be done using the hooks exported from `react-navigation` rather than adding dependency on `@react-navigation/compat` - would you be interested in investigating that? Thank you!

**Comment by JPeer264** [comment]
Ah I already wanted to refactor it to a function component. Sure I will change it to hooks :)

**Comment by euharrison** [comment]
If it's helpful, this is my update:

It exports a hook `useAndroidBackHandler` and a component `<AndroidBackHandler>`

```jsx
import { useCallback } from 'react';
import { BackHandler } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';

export function useAndroidBackHandler(onBackPress) {
  useFocusEffect(
    useCallback(() => {
      BackHandler.addEventListener('hardwareBackPress', onBackPress);

      return () =>
        BackHandler.removeEventListener('hardwareBackPress', onBackPress);
    }, [onBackPress]),
  );
}

export default function AndroidBackHandler({ onBackPress, children }) {
  useAndroidBackHandler(onBackPress);
  return children || null;
}
```

**Comment by JPeer264** [comment]
@euharrison I think your solution to keep the component is pretty nice 👍

**Comment by JPeer264** [comment]
Alright, I updated to hooks and tested them. I updated the README as well.

For the release notes: Upgrading to this should be seamless (if the app is already on `rn-navigation@5`)

**Comment by JPeer264** [comment]
@vonovak ping

**Comment by vonovak** [comment]
@JPeer264 hello and thanks, this looks good to me. Recently, I merged this PR https://github.com/vonovak/react-navigation-backhandler/pull/16 which I think is not covered in this code. Would it possible to support that too, using https://reactnavigation.org/docs/use-is-focused/ ? Thanks!

**Comment by JPeer264** [comment]
Sure thing, I will implement it as well

**Comment by JPeer264** [comment]
@vonovak I checked the [documentation](https://reactnavigation.org/docs/use-focus-effect/) of react-navigation and it says:

> The effect will run whenever the dependencies passed to React.useCallback change, i.e. it'll run on initial render (if the screen is focused) as well as on subsequent renders if the dependencies have changed.

Which means #16 is covered within this PR.

**Comment by vonovak** [comment]
thank you for the PR!

**Pull request merged**
